# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dash Winterson
email: dash@dashwinterson.com
description: > # this means to ignore newlines until "baseurl:"
Experienced software engineer with over 10 years of experience. Expert in design-
ing and implementing scalable and efficient systems. Mentor to junior engineers and

trusted technical project lead. Passionate about using technology to solve complex
problems and staying up-to-date with the latest industry advancements.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dashwinterson.com" # the base hostname & protocol for your site
twitter_username: dashdanw 
github_username:  dashdanw

# Build settings
markdown: kramdown
